Traceback (most recent call last):
  File "/home/hamid/Desktop/Python/Pycharm projects/MatchIT_Labs/test2.py", line 10, in <module>
    raise Exception('the exception occurred')
Exception: the exception occurred
